### ISSUE TITLE
Topic Approval issue

### ISSUE THREAD

**Issue by Sjnaaf** [RMcGirr83/phpBB-3.1-New-Topics-Need-Approval#1]
Hi,

First of all thanks for making this plugin available. Installation went fine. I'm having issues though to get it working. 

There are now two permissions:

"Post" => "Can post without approval"
"Misc" => "Can start new topics without approval"

If I get this correctly then the combination of these two permissions should determine which posts should be approved and which not. I tested all combinations and got the following results.

| Permission "Can start new topics without approval" set to | Permission "Can post without approval" set to | Expected Result: New topic has to be approved | Actual Result: New topic has to be approved | Expected Result: Subsequent posts have to be approved | Actual Result: Subsequent posts have to be approved |
| --- | --- | --- | --- | --- | --- |
| yes | yes | no | no | no | no |
| no | no | yes | yes | yes | yes |
| no | yes | yes | **no** | no | no |
| yes | no | no | **yes** | yes | yes |

This extension currently seems to be resulting in absolutely no effect.

**Comment by Sjnaaf** [comment]
DOH! I forgot to clear the cache. It works as expected. Thanks for this contribution!

**Comment by rmcgirr83** [comment]
Yeah, I should probably put something in the instructions to state to clear the cache.
