### ISSUE TITLE
Default value "yes"

### ISSUE THREAD

**Issue by Sjnaaf** [RMcGirr83/phpBB-3.1-New-Topics-Need-Approval#2]
The default value for this permission in forums where no role is assigned currently is "No". Probably because there is no value for this permission. 

Maybe its better to reverse the workings of the permission and change the description to "New topics need approval". Then the default value of no has no effect.

**Comment by rmcgirr83** [comment]
I am not understanding what you are saying.  The permissions are set based on roles.
`array('permission.permission_set', array('ROLE_FORUM_FULL', 'f_topic_approve')),
            array('permission.permission_set', array('ROLE_FORUM_LIMITED', 'f_topic_approve')),
            array('permission.permission_set', array('ROLE_FORUM_LIMITED_POLLS', 'f_topic_approve')),
            array('permission.permission_set', array('ROLE_FORUM_STANDARD', 'f_topic_approve')),
            array('permission.permission_set', array('ROLE_FORUM_POLLS', 'f_topic_approve')),
            array('permission.permission_set', array('ROLE_FORUM_ONQUEUE', 'f_topic_approve', 'role', false)),`

So naturally if a role hasn't been assigned to a group for a forum then the default of "Can post new topics without approval" will be set to no.

It's exactly the same as the original 3.0 mod.

**Comment by Sjnaaf** [comment]
Ok, let me put it differently. Wouldn't it be more logical to have a default of "yes" since this was the default behaviour before someone installed your extension?

**Comment by rmcgirr83** [comment]
If a group has a role set as "No role assigned" there is no permission to set as that role doesn't exist in the database.  All the roles I stated above are set to yes with the exception of ROLE_FORUM_ONQUEUE which is set to no.  I am not sure how to set the permission to yes for the "No role assigned" designation.  No role will always default to no.

Only way I can think of is to query the groups table, query the forums table and apply yes to those groups and forums in the acl_groups table.  This may become quite the large query in terms of sql commits depending on the number of groups and forums within a phpbb forum.

**Comment by Sjnaaf** [comment]
exactly. Thats why I proposed to reverse the the description of the permission into "New topics need approval". That would also need a code change to reverse the effect of the permission. Then the out-of-the-box default value of no would be ok. No queries needed.

**Comment by rmcgirr83** [comment]
So you would want that each forum would have to be manually set to yes for users on your forum to be able to post without being moderated on?  Are you sure about that?

**Comment by rmcgirr83** [comment]
Please keep in mind this extension is for more than just you :smile:

**Comment by Sjnaaf** [comment]
I would rather like to see a default value of NO for a permission thats called "New topics need approval" than a default value of NO for a permission thats called "Can start new topics without approval" which is now the case.

So all you would be doing is changing how the permission is called and handling its value the other way around inside your extension's code. The default of NO can then remain as it is.

``` php
if ($mode == 'post' && !$this->auth->acl_get('f_topic_approve', $data_array['forum_id']))
```

would be changed to 

``` php
if ($mode == 'post' && $this->auth->acl_get('f_topic_approve', $data_array['forum_id']))
```

which somehow seems more natural to me

**Comment by Sjnaaf** [comment]
I'm aware that this extension is not just for me. All I'm saying is that I doubt the way this default is currently handled. It is somewhere in between of the two. After I install a module that gives me a new permission based feature I find it more natural to enable this permission explicitly where I would need it.

**Comment by rmcgirr83** [comment]
> than a default value of NO for a permission thats called "Can start new topics without approval" which is now the case.

But that is only the case if the role for whichever forum are set to `No role assigned` if the forum permissions are set per a role, then the permission is set to yes which seems more appropriate and logical to me.

Further the change you stated for the trigger would have the reverse affect.

`if ($mode == 'post' && $this->auth->acl_get('f_topic_approve', $data_array['forum_id']))` says, basically, if the mode is post and one has the auth in the forum then do the following which is
`$data_array['force_approved_state'] = ITEM_UNAPPROVED;` which then sets the post into the moderation queue.

I honestly think this is much ado about nothing.  Many administrators of forums won't even touch the permissions...maybe for a few forums but the majority will assign roles to them which this extension will then use and be applied appropriately for.

**Comment by Sjnaaf** [comment]
I see your point and I think we agree on what the default should be. The part I think you are missing is that I suggested three things:
1. Rename the permission from "Can start new topics without approval" to "New topics need approval"
2. code change as you quoted
3. set no defaults at all, resulting in a default of NO

So by reversing the description of the permission AND by reversing how the value of the permission is interpreted in code and setting no defaults at all we end up with the same behaviour except that no migration is needed to set defaults for the same effect. Bonus: it also works when no roles are assigned.

New topics need approval: NO
and
Can start new topics without approval: YES
are exactly the same things

**Comment by rmcgirr83** [comment]
Try https://github.com/RMcGirr83/phpBB-3.1-New-Topics-Need-Approval/tree/reverse_logic

**Comment by Sjnaaf** [comment]
Brilliant!

**Comment by bissim** [comment]
Honestly, I can't get the reason why the permission had to be changed, aborting the “Can start new topics without approval” formulation that well-fitted other core permissions like “can post without approval”; it was more pointful to have it like that and “Yes” as default option, so that once activated the administrator(s) had to manually set it where needed to get it working.

I was about to open an issue to ask it to be renamed, I guess it would be pointless now. I'll open another one to ask it to be put into the _Post_ permission family though.
