### ISSUE TITLE
Be able to control topics approval for replies too

### ISSUE THREAD

**Issue by ferrannp** [RMcGirr83/phpBB-3.1-New-Topics-Need-Approval#5]
Hello and thank you for this extension! I'll explain you my case, I'd like to have a subforum with the following features:
1. For a user to create a new topic, it needs approval
2. When an user edits an own post, it doesn't need approval
3. When an user replies to a post he/she has never replied before, then it needs approval 

With your extension, I am able to achieve 1 and 2 but not 3. I also tried this extension https://github.com/gn36/phpbb-ext-firstpostedit/issues/8 but it doesn't deal with post approval.

Do you think it makes sense to add 3) as a possibility for your extension? Have control of:
- If user replies to a topic that he/she has not been approved to reply, then it needs approval
- If user replies to an own topic or a topic he/she already have been approved to reply, then it doesn't need approval

What do you think?

**Comment by rmcgirr83** [comment]
That isn't the purpose of this extension.  This is a port of this mod https://www.phpbb.com/community/viewtopic.php?t=1346425 and I am not sure what the purpose would be to also force replies/quotes etc to also be approved.  If you are having an issue with a particular user, simply put them on moderation queue.
