### ISSUE TITLE
Move permission into Post group

### ISSUE THREAD

**Issue by bissim** [RMcGirr83/phpBB-3.1-New-Topics-Need-Approval#6]
Hello @RMcGirr83,
I think this permission would fit more into the Post group than in the Misc one, since despite the name it collects both post and topic permissions.

**Comment by rmcgirr83** [comment]
It only affects new topics. Can be moved though to the post settings. Would have been nice if the input provided was provided earlier.

**Comment by rmcgirr83** [comment]
Simply change this line in the listener file

`$permissions['f_topic_approve'] = array('lang' => 'ACL_F_TOPIC_APPROVE', 'cat' => 'misc');`

to this
`$permissions['f_topic_approve'] = array('lang' => 'ACL_F_TOPIC_APPROVE', 'cat' => 'post');`

**Comment by bissim** [comment]
It's pointless if I have to perform the edit every time I update the extension.
Nevermind, I'll stick with things the way they are right now. Thank you anyway.

**Comment by rmcgirr83** [comment]
I don't plan on updating the extension. You are free to take the code and
do with it as you will
