### ISSUE TITLE
Error on phpBB3.3

### ISSUE THREAD

**Issue by MonkeyDZeke** [RMcGirr83/phpBB-3.1-New-Topics-Need-Approval#8]
`[phpBB Debug] PHP Warning: in file [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php on line 214: call_user_func() expects parameter 1 to be a valid callback, class 'rmcgirr83/newtopicsneedapproval/event/listener' does not have a method 'user_setup_after'` is showing above the header on the ACP.

**Comment by rmcgirr83** [comment]
Sorry about that
https://github.com/rmcgirr83/newtopicsneedapproval/commit/ea871d28cc69b9ee5d56c75f1f4f7fe9a20008d6

**Comment by MonkeyDZeke** [comment]
Thanks a million!
